/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.examples.clients.basicavro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum units {
  ns, mus, ms, s  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"units\",\"namespace\":\"io.confluent.examples.clients.basicavro\",\"symbols\":[\"ns\",\"mus\",\"ms\",\"s\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
