/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.vf.examples.clients.basicavro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** original */
@org.apache.avro.specific.AvroGenerated
public class Cancelation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8317030210766832004L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Cancelation\",\"namespace\":\"io.vf.examples.clients.basicavro\",\"doc\":\"original\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"contract_id\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Cancelation> ENCODER =
      new BinaryMessageEncoder<Cancelation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Cancelation> DECODER =
      new BinaryMessageDecoder<Cancelation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Cancelation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Cancelation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Cancelation>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Cancelation to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Cancelation from a ByteBuffer. */
  public static Cancelation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence contract_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Cancelation() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param contract_id The new value for contract_id
   */
  public Cancelation(java.lang.CharSequence id, java.lang.CharSequence contract_id) {
    this.id = id;
    this.contract_id = contract_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return contract_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: contract_id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'contract_id' field.
   * @return The value of the 'contract_id' field.
   */
  public java.lang.CharSequence getContractId() {
    return contract_id;
  }

  /**
   * Sets the value of the 'contract_id' field.
   * @param value the value to set.
   */
  public void setContractId(java.lang.CharSequence value) {
    this.contract_id = value;
  }

  /**
   * Creates a new Cancelation RecordBuilder.
   * @return A new Cancelation RecordBuilder
   */
  public static io.vf.examples.clients.basicavro.Cancelation.Builder newBuilder() {
    return new io.vf.examples.clients.basicavro.Cancelation.Builder();
  }

  /**
   * Creates a new Cancelation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Cancelation RecordBuilder
   */
  public static io.vf.examples.clients.basicavro.Cancelation.Builder newBuilder(io.vf.examples.clients.basicavro.Cancelation.Builder other) {
    return new io.vf.examples.clients.basicavro.Cancelation.Builder(other);
  }

  /**
   * Creates a new Cancelation RecordBuilder by copying an existing Cancelation instance.
   * @param other The existing instance to copy.
   * @return A new Cancelation RecordBuilder
   */
  public static io.vf.examples.clients.basicavro.Cancelation.Builder newBuilder(io.vf.examples.clients.basicavro.Cancelation other) {
    return new io.vf.examples.clients.basicavro.Cancelation.Builder(other);
  }

  /**
   * RecordBuilder for Cancelation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Cancelation>
    implements org.apache.avro.data.RecordBuilder<Cancelation> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence contract_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.vf.examples.clients.basicavro.Cancelation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contract_id)) {
        this.contract_id = data().deepCopy(fields()[1].schema(), other.contract_id);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Cancelation instance
     * @param other The existing instance to copy.
     */
    private Builder(io.vf.examples.clients.basicavro.Cancelation other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contract_id)) {
        this.contract_id = data().deepCopy(fields()[1].schema(), other.contract_id);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.vf.examples.clients.basicavro.Cancelation.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.vf.examples.clients.basicavro.Cancelation.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'contract_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getContractId() {
      return contract_id;
    }

    /**
      * Sets the value of the 'contract_id' field.
      * @param value The value of 'contract_id'.
      * @return This builder.
      */
    public io.vf.examples.clients.basicavro.Cancelation.Builder setContractId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.contract_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'contract_id' field has been set.
      * @return True if the 'contract_id' field has been set, false otherwise.
      */
    public boolean hasContractId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'contract_id' field.
      * @return This builder.
      */
    public io.vf.examples.clients.basicavro.Cancelation.Builder clearContractId() {
      contract_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Cancelation build() {
      try {
        Cancelation record = new Cancelation();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.contract_id = fieldSetFlags()[1] ? this.contract_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Cancelation>
    WRITER$ = (org.apache.avro.io.DatumWriter<Cancelation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Cancelation>
    READER$ = (org.apache.avro.io.DatumReader<Cancelation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
